/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FlavoursRouteImport } from './routes/flavours'
import { Route as FragrancesRouteImport } from './routes/fragrances'
import { Route as GlobalPresenceRouteImport } from './routes/global-presence'
import { Route as NewsRouteImport } from './routes/news'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as NewsYearRouteImport } from './routes/news.$year'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FlavoursRoute = FlavoursRouteImport.update({
  id: '/flavours',
  path: '/flavours',
  getParentRoute: () => rootRouteImport,
} as any)
const FragrancesRoute = FragrancesRouteImport.update({
  id: '/fragrances',
  path: '/fragrances',
  getParentRoute: () => rootRouteImport,
} as any)
const GlobalPresenceRoute = GlobalPresenceRouteImport.update({
  id: '/global-presence',
  path: '/global-presence',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsYearRoute = NewsYearRouteImport.update({
  id: '/$year',
  path: '/$year',
  getParentRoute: () => NewsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/flavours': typeof FlavoursRoute
  '/fragrances': typeof FragrancesRoute
  '/global-presence': typeof GlobalPresenceRoute
  '/news': typeof NewsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/news/$year': typeof NewsYearRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/flavours': typeof FlavoursRoute
  '/fragrances': typeof FragrancesRoute
  '/global-presence': typeof GlobalPresenceRoute
  '/news': typeof NewsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/news/$year': typeof NewsYearRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/flavours': typeof FlavoursRoute
  '/fragrances': typeof FragrancesRoute
  '/global-presence': typeof GlobalPresenceRoute
  '/news': typeof NewsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/news/$year': typeof NewsYearRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/flavours'
    | '/fragrances'
    | '/global-presence'
    | '/news'
    | '/sitemap.xml'
    | '/news/$year'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/flavours'
    | '/fragrances'
    | '/global-presence'
    | '/news'
    | '/sitemap.xml'
    | '/news/$year'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/flavours'
    | '/fragrances'
    | '/global-presence'
    | '/news'
    | '/sitemap.xml'
    | '/news/$year'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  FlavoursRoute: typeof FlavoursRoute
  FragrancesRoute: typeof FragrancesRoute
  GlobalPresenceRoute: typeof GlobalPresenceRoute
  NewsRoute: typeof NewsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flavours': {
      id: '/flavours'
      path: '/flavours'
      fullPath: '/flavours'
      preLoaderRoute: typeof FlavoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fragrances': {
      id: '/fragrances'
      path: '/fragrances'
      fullPath: '/fragrances'
      preLoaderRoute: typeof FragrancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/global-presence': {
      id: '/global-presence'
      path: '/global-presence'
      fullPath: '/global-presence'
      preLoaderRoute: typeof GlobalPresenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$year': {
      id: '/news/$year'
      path: '/$year'
      fullPath: '/news/$year'
      preLoaderRoute: typeof NewsYearRouteImport
      parentRoute: typeof NewsRoute
    }
  }
}

interface NewsRouteChildren {
  NewsYearRoute: typeof NewsYearRoute
}

const NewsRouteChildren: NewsRouteChildren = {
  NewsYearRoute: NewsYearRoute,
}

const NewsRouteWithChildren = NewsRoute._addFileChildren(NewsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  FlavoursRoute: FlavoursRoute,
  FragrancesRoute: FragrancesRoute,
  GlobalPresenceRoute: GlobalPresenceRoute,
  NewsRoute: NewsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
